from pathlib import Path
p=Path('app.py'); s=p.read_text()
start=s.index("@st.dialog('Full Calculation Workings'")
end=s.index("@st.dialog('Full Data Audit'",start)
new=r'''@st.dialog('Complete Quantitative Workings',width='large')
def show_latex_report():
 st.title('Complete Quantitative Workings')
 st.caption(f'Configured run: {prices.index[0]:%Y-%m-%d} to {prices.index[-1]:%Y-%m-%d} | frequency={frequency} | N={ppy} | RF={RF:.4%} | observations={len(prices)} | mode={mode}')
 st.header('1. Data state, units and reconstructed returns')
 st.latex(r'P_{i,t}=\text{raw close price},\quad D_{i,t}=\text{cash distribution per unit},\quad S_{i,t}=\text{split event}')
 st.latex(r'r_{i,t}=\frac{P_{i,t}-P_{i,t-1}+D_{i,t}}{P_{i,t-1}}')
 st.latex(r'R^{cap}_i=\frac{P_{i,T}-P_{i,0}}{P_{i,0}},\quad R^{inc}_i=\frac{\sum_{t=1}^{T}D_{i,t}}{P_{i,0}},\quad R^{tot}_i=R^{cap}_i+R^{inc}_i')
 st.latex(r'\omega^{cap}_i=R^{cap}_i/R^{tot}_i,\quad \omega^{inc}_i=R^{inc}_i/R^{tot}_i')
 st.write('Adjusted Close is not used. Distributions are explicit. Split events are captured explicitly. STXGVI uses the validated cents/ZAR normalisation before reconstruction. No automatic FX overlay is applied.')
 st.dataframe(pd.DataFrame({'Instrument':[instrument_names.get(i,i) for i in ASSETS],'Ticker / Series':ASSETS,'Initial Price':[prices[i].iloc[0] for i in ASSETS],'Final Price':[prices[i].iloc[-1] for i in ASSETS],'Cash Distributions':[divs[i].iloc[1:].sum() for i in ASSETS]}),hide_index=True,use_container_width=True)
 st.header('2. Portfolio initialisation and accounting identity')
 st.latex(r'A_{i,0}=w_iV_0,\qquad q_{i,0}=\frac{A_{i,0}}{P_{i,0}},\qquad \sum_iw_i=1')
 st.latex(r'I_{i,t}=q_{i,t-1}D_{i,t}')
 st.latex(r'q_{i,t}=q_{i,t-1}+\frac{I_{i,t}}{P_{i,t}}\quad\text{(reinvestment)}')
 st.latex(r'C_{i,t}=C_{i,t-1}+I_{i,t}\quad\text{(income retained as cash)}')
 st.latex(r'V_{i,t}=q_{i,t}P_{i,t}+C_{i,t},\qquad V_t=\sum_iV_{i,t}')
 st.write(f'Nominal V0 = {INITIAL:,.2f}; reinvest distributions = {REINVEST}.')
 st.header('3. Annual rebalancing')
 st.latex(r'w_i^*=\frac{A_{i,0}}{V_0},\qquad q_{i,t^+}=\frac{w_i^*V_{t^-}}{P_{i,t^-}},\qquad C_{i,t^+}=0')
 st.write('Rebalancing is applied at the first observation of a new calendar year when Annual Rebalanced mode is selected.')
 st.header('4. Portfolio and annual total return')
 st.latex(r'r_{p,t}=\frac{V_t}{V_{t-1}}-1,\qquad R_{p,0:T}=\frac{V_T}{V_0}-1')
 st.latex(r'R_{p,y}=\frac{V_{y,end}}{V_{y,start}}-1')
 st.latex(r'R_{i,y}=\frac{P_{i,end}-P_{i,start}+\sum_{t\in y}D_{i,t}}{P_{i,start}}')
 st.header('5. CAGR and elapsed-time convention')
 st.latex(r'Y=\frac{T_{end}-T_{start}}{365.25},\qquad CAGR=\left(\frac{V_T}{V_0}\right)^{1/Y}-1')
 st.write(f'Current CAGR = {met["CAGR"]:.6%}; elapsed observations = {len(prices)}.')
 st.header('6. Volatility and risk-free transformation')
 st.latex(r'N=252\ \text{(daily)}\quad\text{or}\quad N=12\ \text{(month-end)}')
 st.latex(r'\sigma_{ann}=s(r_p)\sqrt{N}')
 st.latex(r'r_{f}=\left(1+R_f\right)^{1/N}-1,\qquad e_t=r_{p,t}-r_f')
 st.write(f'Current N={ppy}; annual RF={RF:.6%}; periodic RF={(1+RF)**(1/ppy)-1:.8%}; annualised volatility={met["Annualised Volatility"]:.6%}.')
 st.header('7. Sharpe ratio')
 st.latex(r'Sharpe=\frac{\bar e}{s(e)}\sqrt{N}')
 st.write(f'Current Sharpe = {met["Sharpe Ratio"]:.6f}.')
 st.header('8. Downside deviation and Sortino')
 st.latex(r'\mathcal D=\{t:e_t<0\},\qquad \sigma_{down}=\sqrt{\frac{1}{|\mathcal D|}\sum_{t\in\mathcal D}e_t^2}\sqrt N')
 st.latex(r'Sortino=\frac{\bar e\,N}{\sigma_{down}}')
 st.write(f'Downside volatility={met["Downside Volatility"]:.6%}; Sortino={met["Sortino Ratio"]:.6f}.')
 st.header('9. Drawdown, maximum drawdown and Calmar')
 st.latex(r'H_t=\max_{s\le t}V_s,\qquad DD_t=\frac{V_t}{H_t}-1,\qquad MDD=\min_tDD_t')
 st.latex(r'Calmar=\frac{CAGR}{|MDD|}')
 st.write(f'MDD={met["Maximum Drawdown"]:.6%}; MDD date={met["Max DD Date"]:%Y-%m-%d}; Calmar={met["Calmar Ratio"]:.6f}.')
 st.header('10. Historical VaR and CVaR / Expected Shortfall')
 st.latex(r'VaR_{95}=Q_{0.05}(r_p)')
 st.latex(r'CVaR_{95}=E[r_p\mid r_p\le VaR_{95}]')
 st.write(f'VaR95={met["Period VaR 95%"]:.6%}; CVaR95={met["Period CVaR 95%"]:.6%}.')
 st.header('11. Empirical return diagnostics')
 st.latex(r'r_{best}=\max_t r_{p,t},\quad r_{worst}=\min_t r_{p,t},\quad p_+=\frac{\sum_t\mathbf 1(r_{p,t}>0)}{T}')
 st.write(f'Best={met["Best Period"]:.6%}; worst={met["Worst Period"]:.6%}; positive periods={met["Positive Periods"]:.6%}.')
 st.header('12. Rolling one-year total return')
 st.latex(r'R^{(L)}_{p,t}=\prod_{j=0}^{L-1}(1+r_{p,t-j})-1')
 st.write(f'L={roll_n} observations.')
 st.header('13. Rolling annualised volatility')
 st.latex(r'\sigma^{(L)}_{p,t}=s(r_{p,t-L+1:t})\sqrt N')
 st.header('14. Rolling three-year Sharpe')
 st.latex(r'Sharpe^{(W)}_t=\frac{\overline e_{t-W+1:t}}{s(e_{t-W+1:t})}\sqrt N')
 st.write(f'W={sharpe_n} observations.')
 st.header('15. Portfolio sleeve weights and drift')
 st.latex(r'w_{i,t}=\frac{V_{i,t}}{V_t},\qquad \Delta w_{i,t}=w_{i,t}-w_{i,0}')
 st.dataframe(wt,hide_index=True,use_container_width=True)
 st.header('16. Pearson covariance and correlation matrix')
 st.latex(r'Cov_{ij}=\frac{1}{T-1}\sum_{t=1}^{T}(r_{i,t}-\bar r_i)(r_{j,t}-\bar r_j)')
 st.latex(r'\rho_{ij}=\frac{Cov_{ij}}{s_i s_j}')
 st.latex(r'\bar\rho=\frac{2}{K(K-1)}\sum_{i<j}\rho_{ij}')
 st.write('The page heatmap is the Pearson matrix computed from the same reconstructed periodic asset returns.')
 st.dataframe(corr,use_container_width=True)
 st.write('Net inter-asset correlation = '+('N/A' if not np.isfinite(net_corr) else f'{net_corr:.6f}'))
 st.header('17. CAPM beta')
 st.latex(r'x_t=r_{m,t}-r_f,\qquad y_t=r_{p,t}-r_f,\qquad \beta=\frac{Cov(y,x)}{Var(x)}')
 st.write(f'Benchmark={BENCHMARK_TICKER}; current beta={met["Beta vs ALSI"]:.6f}.')
 st.header('18. CAPM alpha')
 st.latex(r'\alpha_{period}=\bar y-\beta\bar x')
 st.latex(r'\alpha_{ann}=(1+\alpha_{period})^N-1')
 st.write(f'Current annualised alpha={met["CAPM Alpha (Annualised)"]:.6%}.')
 st.header('19. Rolling beta and rolling alpha')
 st.latex(r'\beta_t^{(W)}=\frac{Cov(y,x)_{t-W+1:t}}{Var(x)_{t-W+1:t}}')
 st.latex(r'\alpha_{t,period}^{(W)}=\bar y^{(W)}_t-\beta_t^{(W)}\bar x^{(W)}_t,\qquad \alpha_{t,ann}^{(W)}=(1+\alpha_{t,period}^{(W)})^N-1')
 st.write(f'Rolling CAPM window={capm_window} observations.')
 st.header('20. Conditional beta in benchmark stress')
 st.latex(r'DD^m_t=\frac{P^m_t}{\max_{s\le t}P^m_s}-1')
 st.latex(r'\mathcal S=\{t:DD^m_t\le-10\%\},\qquad \beta_{cond}=\frac{Cov(r_p,r_m\mid t\in\mathcal S)}{Var(r_m\mid t\in\mathcal S)}')
 st.write(f'Conditional beta='+('N/A' if not np.isfinite(cb) else f'{cb:.6f}')+f'; stress observations={ncb}.')
 st.header('21. Return attribution by instrument')
 st.latex(r'R_i^{tot}=R_i^{cap}+R_i^{inc},\qquad 1=\frac{R_i^{cap}}{R_i^{tot}}+\frac{R_i^{inc}}{R_i^{tot}}')
 st.dataframe(at,hide_index=True,use_container_width=True)
 st.header('22. Complete configured metric output')
 st.dataframe(metric_table(met),hide_index=True,use_container_width=True)

'''
s=s[:start]+new+s[end:]
s=s.replace("if latex_slot.button('LaTeX',use_container_width=True): show_latex_report()","if latex_slot.button('Show LaTeX',use_container_width=True): show_latex_report()")
p.write_text(s)
